name: Run Inventory Management Script

# Trigger the workflow on push to any branch
on: [push]
env:
  cloud: GCP
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any dependencies here (if you have any in a requirements.txt file)
          # pip install -r requirements.txt

      - name: Run inventory script
        run: |
            python inventory.py
            echo "my cloud is $cloud"
